### ISSUE TITLE
Use Meson as a build system

### ISSUE THREAD

**Issue by kena-e8ac99** [kena-e8ac99/Ami#2]
- [x] Add meson.build file and make the following settings in it.
- Use C++20
- Set the warning level to 3 (maximum)
- Include "include" directory

- [x] Add the following directories to .gitignore
- .cache

**Comment by eli-schwartz** [comment]
You do not need to add the `build/` directory to gitignore, since:
- it could be named `builddir/` (this is actually preferred in the Meson documentation for clarity purposes)
- a major touted feature of Meson is that due to out of tree builds, you can have several different build directories with different configurations
- meson will generate a gitignore file in each build directory, which ignores all files :D since Meson knows when it is creating a build directory, and knows that all files in that directory are obviously generated artifacts which shall not be checked into git. So it tries to be helpful and do the right thing.

**Comment by kena-e8ac99** [comment]
Thank you for your comment.

> meson will generate a gitignore file in each build directory, which ignores all files

-> I have confirmed the above and removed the following from this issue.
- Add the `build/` directory to gitignore
